id: A1DBF0186
base_file: fB2BD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.983170
  last_modified_at: 2022-05-30 21:43:24.983173
