id: A1DBF0186
base_file: fD31E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.990719
  last_modified_at: 2022-05-30 21:43:24.990722
