id: A1DBF0186
base_file: fEF03.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:25.009778
  last_modified_at: 2022-05-30 21:43:25.009781
