id: A1DBF0186
base_file: fE4E6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:25.006318
  last_modified_at: 2022-05-30 21:43:25.006321
