id: A1DBF0186
base_file: f26DC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.892840
  last_modified_at: 2022-05-30 21:43:24.892844
