id: A1DBF0186
base_file: f7A88.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.952730
  last_modified_at: 2022-05-30 21:43:24.952733
