id: A1DBF0186
base_file: f6EB9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.941980
  last_modified_at: 2022-05-30 21:43:24.941991
