id: A1DBF0186
base_file: f3F0A.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.913219
  last_modified_at: 2022-05-30 21:43:24.913224
