id: A1DBF0186
base_file: fDB02.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.997220
  last_modified_at: 2022-05-30 21:43:24.997223
