id: A1DBF0186
base_file: f1EEA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.888742
  last_modified_at: 2022-05-30 21:43:24.888745
