id: A1DBF0186
base_file: fF604.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:25.011194
  last_modified_at: 2022-05-30 21:43:25.011197
