id: A1DBF0186
base_file: f6652.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.935513
  last_modified_at: 2022-05-30 21:43:24.935523
