id: A1DBF0186
base_file: f7A4A.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.950903
  last_modified_at: 2022-05-30 21:43:24.950906
