id: A1DBF0186
base_file: f8A17.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:43:24.957505
  last_modified_at: 2022-05-30 21:43:24.957508
